title: AutoSugar
description: Blood glucose monitoring for Android Auto
url: "https://autosugar.de"
theme: minima

header_pages:
  - install.md
  - privacy-policy.md

exclude:
  - adr/

minima:
  skin: auto
  logo: /assets/logo.png
